### PR TITLE
Feature helm test QuantumLeap

### PR DESCRIPTION
**Pull request by ernesgonzalez33**

### CODE REVIEW

**Comment by jtudelag** [comment]
Can you add the annotations to the test,as here? https://github.com/FIWARE-Ops/marinera/blob/main/applications/orion-ld/chart/orion-ld/templates/tests/orion-test.yaml#L7

**Comment by ernesgonzalez33** [comment]
@jtudelag annotations added and created a new test for the timescale connection

**Comment by jtudelag** [comment]
LGTM!

**Review by jtudelag — APPROVED** [review]
LGTM

**Pull request merged**
