### PR TITLE
Update datasource-checker.json

### PR DESCRIPTION
**Pull request by wistefan**
Quantum leap stores data in etairqualityobserved instead of mttest.etairqualityobserved
See:
```shell
       table_name       |                                                                                      entity_attrs                                                                                      
------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 "mttest"."ettest"      | {"test": ["test", "Number"], "entity_id": ["id", "Text"], "time_index": ["time_index", "DateTime"], "entity_type": ["type", "Text"]}
 "etairqualityobserved" | {"humidity": ["humidity", "Number"], "entity_id": ["id", "Text"], "time_index": ["time_index", "DateTime"], "entity_type": ["type", "Text"], "temperature": ["temperature", "Number"]}

```

### CODE REVIEW

**Comment by wistefan** [comment]
> @arturohu please double check this when you have time, I think you know the QL..

I did investigate that a little today and found out about the problem. The subscription I got from @versatildefuy  does not forward the fiware-servicepath and fiware-service header to quantumleap. Therefore they are not included in the tablename and it has to be removed. I'm not sure if thats the expected behaviour or if we need to fix something in the subscription.

**Comment by wistefan** [comment]
I got the service part solved: https://github.com/FIWARE-Ops/marinera-e2e/blob/main/src/test/java/org/fiware/marinerae2e/StepDefinitions.java#L300-L302

**Comment by ernesgonzalez33** [comment]
> I got the service part solved: https://github.com/FIWARE-Ops/marinera-e2e/blob/main/src/test/java/org/fiware/marinerae2e/StepDefinitions.java#L300-L302 So we can use it either with or without, it only needs to be consistent.

So do we still need this PR?

**Comment by arturohu** [comment]
> I got the service part solved: https://github.com/FIWARE-Ops/marinera-e2e/blob/main/src/test/java/org/fiware/marinerae2e/StepDefinitions.java#L300-L302 So we can use it either with or without, it only needs to be consistent.

We normally create the subscription in a Fiware-Service and Fiware-Servicepath. The obtained subscription notifications always include the Fwiare-Service and Fiware-Servicepath headers where its subscription was created. 

So we do not need to specify the fiware-service and fiware-servicepath in each subscription.

**Pull request closed without merging**
